# Generated by Django 5.0.6 on 2024-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_employee_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="additional_info",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo_url",
            field=models.URLField(null=True),
        ),
    ]
