# Generated by Django 5.0.6 on 2024-05-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
