# Generated by Django 5.0.6 on 2024-05-26 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_employee_photo_url_employee_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="profile",
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
