# Generated by Django 5.0.6 on 2024-05-27 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_client_profile_employee_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="birth",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="birth",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
