# Generated by Django 5.0.6 on 2024-05-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0004_remove_client_profile_remove_client_user_and_more"),
        ("users", "0006_remove_client_profile_employee_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="address",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="email",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="agent",
            name="employee",
            field=models.OneToOneField(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
            ),
            preserve_default=False,
        ),
    ]
