# Generated by Django 5.0.6 on 2024-05-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0005_remove_agent_address_remove_agent_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancecontract",
            name="branch",
        ),
        migrations.AddField(
            model_name="agent",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name="insurancecontract",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="insurance_system.agent",
            ),
        ),
    ]
