# Generated by Django 5.0.6 on 2024-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "insurance_system",
            "0007_insuranceobject_type_alter_insuranceobject_client_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insuranceobject",
            name="client",
        ),
    ]
