# Generated by Django 5.0.6 on 2024-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0008_remove_insuranceobject_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceobject",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
