# Generated by Django 5.0.6 on 2024-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0009_alter_insuranceobject_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceobject",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
