# Generated by Django 5.0.6 on 2024-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0010_alter_insuranceobject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceobject",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
