# Generated by Django 5.0.6 on 2024-05-27 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0011_alter_insuranceobject_name"),
        ("users", "0007_client_birth_employee_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="insurancecontract",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="insurancecontract",
            name="start_date",
        ),
        migrations.CreateModel(
            name="ClientContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.client"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance_system.insurancecontract",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="insurancecontract",
            name="clients",
            field=models.ManyToManyField(
                through="insurance_system.ClientContract", to="users.client"
            ),
        ),
        migrations.DeleteModel(
            name="ClientAgent",
        ),
    ]
