# Generated by Django 5.0.6 on 2024-05-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0012_remove_agent_clients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancecontract",
            name="insurance_amount",
        ),
        migrations.AddField(
            model_name="clientcontract",
            name="insurance_amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
