# Generated by Django 5.0.6 on 2024-05-27 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0013_remove_insurancecontract_insurance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecontract",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
