# Generated by Django 5.0.6 on 2024-05-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0014_insurancecontract_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="salary",
        ),
    ]
