# Generated by Django 5.0.6 on 2024-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0015_remove_agent_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="agents_salary",
            field=models.FloatField(default=0),
        ),
    ]
