# Generated by Django 5.0.6 on 2024-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_system", "0016_clientcontract_agents_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontract",
            name="discount",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
