# Generated by Django 5.0.6 on 2024-05-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "company_info",
            "0002_about_created_at_about_updated_at_article_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="datetime",
        ),
    ]
