# Generated by Django 5.0.6 on 2024-05-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0004_employee_user"),
        ("users", "0002_profile_employee_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.client",
            ),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
