# Generated by Django 5.0.6 on 2024-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0005_alter_review_client_delete_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
        migrations.AddField(
            model_name="about",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="about",
            name="video_url",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="short_description",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
